project_name: age-classifier
notes: 
use_wandb: True
wandb_entity: winniethepooh

annot_dir: /proj/nobackup/aiforeagles/AgeClassifier/annot
outdir: /proj/nobackup/aiforeagles/AgeClassifier/results
dataset: /proj/nobackup/aiforeagles/artportalen/data

model_name: resnet152
checkpoint: None
batch_size: 32
img_size: 256
epochs: 100
save_interval: 10
n_gpu: 1
num_workers: 12
gpu_ids: None
seed: 42


local_checkpoint_interval: 10
max_epochs: 100

transforms:
  mean: 0.5
  std: 0.5

early_stopping:
  monitor: val/loss
  min_delta: 0.001
  patience: 10
  verbose: true
  mode: min

solver:
  OPT: adam  # adam, sgd
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9  # only when OPT is sgd
  BASE_LR: 0.001
  LR_SCHEDULER: step  # step, multistep, reduce_on_plateau
  LR_DECAY_RATE: 0.1
  LR_STEP_SIZE: 10  # only when LR_SCHEDULER is step
  LR_STEP_MILESTONES: [10, 15]  # only when LR_SCHEDULER is multistep

model: resnet152

# train_dataloader:
#   batch_size: 32
#   num_workers: 4
# val_dataloader:
#   batch_size: 32
#   num_workers: 4
