project_name: age-classifier
notes: 
use_wandb: True
wandb_entity: winniethepooh

annot_dir: /proj/nobackup/aiforeagles/AgeClassifier/annot
outdir: /proj/nobackup/aiforeagles/AgeClassifier/results
dataset: /proj/nobackup/aiforeagles/artportalen/data

model_name: resnet152.a1_in1k
checkpoint: 
batch_size: 32
img_size: 256
epochs: 100
save_interval: 10
n_gpu: 1
num_workers: 12
gpu_ids: 
seed: 42

use_gradcam: False

transforms:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

early_stopping:
  monitor: val/loss
  min_delta: 0.0005
  patience: 10
  verbose: true
  mode: min

solver:
  OPT: adam  # adam, sgd
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9  # only when OPT is sgd
  BASE_LR: 0.001
  LR_SCHEDULER: step  # step, multistep, reduce_on_plateau
  LR_DECAY_RATE: 0.1
  LR_STEP_SIZE: 10  # only when LR_SCHEDULER is step
  LR_STEP_MILESTONES: [10, 15]  # only when LR_SCHEDULER is multistep
